# Basic numpy samples

In [2]:
import numpy as np

In [6]:
np.zeros((2, 4))

array([0., 0., 0., 0.])

# arange
Similar to the ruby range with a step_field. By default the step_field is 1.

In [4]:
np.arange(0,100,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

# Linspace
Creates equally spaced n number of points. It is of the format
```python
def linspace(starting_point, ending_point, total_no_of_points)
```

In [11]:
np.linspace(0,4,100)

array([0.        , 0.04040404, 0.08080808, 0.12121212, 0.16161616,
       0.2020202 , 0.24242424, 0.28282828, 0.32323232, 0.36363636,
       0.4040404 , 0.44444444, 0.48484848, 0.52525253, 0.56565657,
       0.60606061, 0.64646465, 0.68686869, 0.72727273, 0.76767677,
       0.80808081, 0.84848485, 0.88888889, 0.92929293, 0.96969697,
       1.01010101, 1.05050505, 1.09090909, 1.13131313, 1.17171717,
       1.21212121, 1.25252525, 1.29292929, 1.33333333, 1.37373737,
       1.41414141, 1.45454545, 1.49494949, 1.53535354, 1.57575758,
       1.61616162, 1.65656566, 1.6969697 , 1.73737374, 1.77777778,
       1.81818182, 1.85858586, 1.8989899 , 1.93939394, 1.97979798,
       2.02020202, 2.06060606, 2.1010101 , 2.14141414, 2.18181818,
       2.22222222, 2.26262626, 2.3030303 , 2.34343434, 2.38383838,
       2.42424242, 2.46464646, 2.50505051, 2.54545455, 2.58585859,
       2.62626263, 2.66666667, 2.70707071, 2.74747475, 2.78787879,
       2.82828283, 2.86868687, 2.90909091, 2.94949495, 2.98989

## Identity matrix
Simply creates an identity matrix of the size specified

In [13]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## random
Use this to generate random values. Has lots of different methods.

In [14]:
np.random.rand(45)

array([0.22027825, 0.28083725, 0.1699476 , 0.46340071, 0.98504047,
       0.6592311 , 0.5198105 , 0.25519939, 0.36170589, 0.24364091,
       0.253748  , 0.25190236, 0.67927455, 0.38752561, 0.48456628,
       0.62263432, 0.52789258, 0.05356248, 0.53773835, 0.55065707,
       0.12453462, 0.85580693, 0.47241155, 0.54155742, 0.95718676,
       0.52913219, 0.27566408, 0.70536355, 0.51865535, 0.66103595,
       0.06199307, 0.01347255, 0.40312898, 0.90414145, 0.22022773,
       0.63431565, 0.27457954, 0.84726892, 0.28402387, 0.2974652 ,
       0.68461812, 0.86352638, 0.8727155 , 0.2848098 , 0.48033494])

In [15]:
# Random from gaussian distribution
np.random.randn(4,4)

array([[-0.20375373, -0.69520286,  1.17409401, -0.59580585],
       [-1.33673363, -1.25083986, -0.65417931, -0.13953439],
       [ 2.53380683, -0.46708546,  0.15567619,  1.0546063 ],
       [ 1.96204868,  0.88630162, -0.56746188,  0.50548715]])

## reshape
return the same value sets of an array into another matrix or a vector

In [21]:
arr = np.arange(0, 50, 2)

In [22]:
arr.reshape(5,5)

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48]])

## max and min
There are methods like `.max()` & `.min()` which can be used to get the max and min values of an array.
The methods `.argmax()` amd `.argmin()` can be used to get the index of the max and min values.

In [23]:
arr.max()

48

In [24]:
arr.argmax()

24

## shape & reshape
`shape` can be used to get the dimensions of the matrix.
`reshape` can be used to change the dimensions of the matrix

In [25]:
arr.shape

(25,)

In [26]:
arr = arr.reshape(5,5)

In [27]:
arr

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48]])

In [28]:
arr.shape

(5, 5)

## dtype
returns the datatype of the array

In [29]:
arr.dtype

dtype('int64')

# conditions
Conditional matching is quite simple

In [30]:
arr = np.arange(0,10)

In [31]:
bool_arr = arr > 5

In [32]:
bool_arr

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [33]:
arr[arr>5]

array([6, 7, 8, 9])

## Some operations

In [3]:
arr = np.arange(0, 11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [6]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [8]:
arr * 10

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [9]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [10]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [11]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [12]:
np.log(arr)

/home/gsr/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])